// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_closest_center_interface
IntegerVector find_closest_center_interface(NumericMatrix data_mat, NumericMatrix centers_mat);
RcppExport SEXP _RPackage1_find_closest_center_interface(SEXP data_matSEXP, SEXP centers_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data_mat(data_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type centers_mat(centers_matSEXP);
    rcpp_result_gen = Rcpp::wrap(find_closest_center_interface(data_mat, centers_mat));
    return rcpp_result_gen;
END_RCPP
}
// update_centers_interface
NumericMatrix update_centers_interface(NumericMatrix data_mat, IntegerVector cluster_vec, int N_centers);
RcppExport SEXP _RPackage1_update_centers_interface(SEXP data_matSEXP, SEXP cluster_vecSEXP, SEXP N_centersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data_mat(data_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_vec(cluster_vecSEXP);
    Rcpp::traits::input_parameter< int >::type N_centers(N_centersSEXP);
    rcpp_result_gen = Rcpp::wrap(update_centers_interface(data_mat, cluster_vec, N_centers));
    return rcpp_result_gen;
END_RCPP
}
// compare_matricies_interface
int compare_matricies_interface(NumericMatrix x, NumericMatrix y, int N_centers, int N_features);
RcppExport SEXP _RPackage1_compare_matricies_interface(SEXP xSEXP, SEXP ySEXP, SEXP N_centersSEXP, SEXP N_featuresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type N_centers(N_centersSEXP);
    Rcpp::traits::input_parameter< int >::type N_features(N_featuresSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_matricies_interface(x, y, N_centers, N_features));
    return rcpp_result_gen;
END_RCPP
}
// KMeans_interface
IntegerVector KMeans_interface(NumericMatrix data_mat, NumericMatrix centers_mat);
RcppExport SEXP _RPackage1_KMeans_interface(SEXP data_matSEXP, SEXP centers_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data_mat(data_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type centers_mat(centers_matSEXP);
    rcpp_result_gen = Rcpp::wrap(KMeans_interface(data_mat, centers_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RPackage1_find_closest_center_interface", (DL_FUNC) &_RPackage1_find_closest_center_interface, 2},
    {"_RPackage1_update_centers_interface", (DL_FUNC) &_RPackage1_update_centers_interface, 3},
    {"_RPackage1_compare_matricies_interface", (DL_FUNC) &_RPackage1_compare_matricies_interface, 4},
    {"_RPackage1_KMeans_interface", (DL_FUNC) &_RPackage1_KMeans_interface, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RPackage1(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
