# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_closest_center_interface <- function(data_mat, centers_mat) {
    .Call(`_RPackage1_find_closest_center_interface`, data_mat, centers_mat)
}

update_centers_interface <- function(data_mat, cluster_vec, N_centers) {
    .Call(`_RPackage1_update_centers_interface`, data_mat, cluster_vec, N_centers)
}

compare_matricies_interface <- function(x, y, N_centers, N_features) {
    .Call(`_RPackage1_compare_matricies_interface`, x, y, N_centers, N_features)
}

KMeans_interface <- function(data_mat, centers_mat) {
    .Call(`_RPackage1_KMeans_interface`, data_mat, centers_mat)
}

